name: Generate SoH Archive

on:
  push:
    branches: [ "Custom-Music-2.0" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Generate SoH archive
      run: |
        cd data
        find . -type f -name '*.ootrs' | while read filename; do unzip -o -d "./Music/`basename -s .ootrs "$filename"`" "$filename"; done;
        wget https://github.com/leggettc18/SequenceOTRizer/releases/download/v0.3/SequenceOTRizer-0.2-Linux.tar.gz
        tar -xzvf SequenceOTRizer-0.2-Linux.tar.gz
        ./SequenceOTRizer --seq-path Music --otr-name daruniasjoy

    - name: Upload generated daruniasjoy.otr
      uses: actions/upload-artifact@v3
      with:
        name: daruniasjoy.otr
        path: data/mods
